# -*- coding: utf-8 -*-
"""CausalInference3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15rZomLFuyrByYsGVuAl5fpl8pAZ1UCrJ
"""

# ============================
# Customer Segmentation
# ============================

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

from sklearn.metrics import (
    silhouette_score,
    calinski_harabasz_score,
    davies_bouldin_score
)

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

df = pd.read_csv("/content/drive/MyDrive/Telecom_Causal_Inference_Modified_Data.csv")

numerical_features = [
    'tenure',
    'MonthlyCharges',
    'TotalCharges'
]

categorical_features = [
    'SeniorCitizen',
    'Partner',
    'Dependents',
    'InternetService',
    'Contract',
    'OnlineSecurity',
    'TechSupport'
]

customer_features = pd.get_dummies(
    df[numerical_features + categorical_features],
    drop_first=True
)

print(customer_features.shape)
customer_features.head()

scaler = StandardScaler()

X_scaled = scaler.fit_transform(customer_features)

print(X_scaled.shape)

k_values = range(2, 11)

wcss = []
silhouette_scores = []
calinski_scores = []
davies_scores = []

for k in k_values:

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=20
    )

    labels = kmeans.fit_predict(X_scaled)

    wcss.append(kmeans.inertia_)

    silhouette_scores.append(
        silhouette_score(X_scaled, labels)
    )

    calinski_scores.append(
        calinski_harabasz_score(X_scaled, labels)
    )

    davies_scores.append(
        davies_bouldin_score(X_scaled, labels)
    )

evaluation = pd.DataFrame({
    "K": list(k_values),
    "WCSS": wcss,
    "Silhouette": silhouette_scores,
    "Calinski-Harabasz": calinski_scores,
    "Davies-Bouldin": davies_scores
})

evaluation

plt.figure(figsize=(6,4))

plt.plot(k_values, wcss, marker='o')

plt.xlabel("Number of Clusters (K)")
plt.ylabel("WCSS")
plt.title("Elbow Method")

plt.show()

plt.figure(figsize=(6,4))

plt.plot(k_values, silhouette_scores, marker='o')

plt.xlabel("Number of Clusters (K)")
plt.ylabel("Silhouette Score")
plt.title("Silhouette Analysis")

plt.show()

plt.figure(figsize=(6,4))

plt.plot(k_values, calinski_scores, marker='o')

plt.xlabel("Number of Clusters (K)")
plt.ylabel("CH Score")
plt.title("Calinski-Harabasz Index")

plt.show()

plt.figure(figsize=(6,4))

plt.plot(k_values, davies_scores, marker='o')

plt.xlabel("Number of Clusters (K)")
plt.ylabel("DB Score")
plt.title("Davies-Bouldin Index")

plt.show()

for k in [2, 4]:
    km = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=20
    )

    df[f'Cluster_{k}'] = km.fit_predict(X_scaled)

    print(f"\n========== K = {k} ==========")
    print(df[f'Cluster_{k}'].value_counts().sort_index())

for k in [2, 4]:
    print(f"\n========== Cluster Profile (K={k}) ==========\n")

    profile = df.groupby(f'Cluster_{k}')[[
        'tenure',
        'MonthlyCharges',
        'TotalCharges',
        'Received_Offer',
        'Churn_Final_Flag'
    ]].mean()

    print(profile)

# ===============================
# Final KMeans Model
# ===============================

optimal_k = 4

kmeans = KMeans(
    n_clusters=optimal_k,
    random_state=42,
    n_init=20
)

df['Customer_Segment'] = kmeans.fit_predict(X_scaled)

cluster_size = (
    df['Customer_Segment']
    .value_counts()
    .sort_index()
    .rename("Customers")
    .to_frame()
)

cluster_size["Percentage"] = (
    cluster_size["Customers"] /
    len(df) * 100
).round(2)

cluster_size

cluster_profile = df.groupby("Customer_Segment").agg({

    "tenure":"mean",
    "MonthlyCharges":"mean",
    "TotalCharges":"mean",

    "Received_Offer":"mean",
    "Churn_Final_Flag":"mean",

    "SeniorCitizen":"mean"

}).round(2)

cluster_profile.rename(columns={

    "Received_Offer":"Offer Rate",
    "Churn_Final_Flag":"Churn Rate",
    "SeniorCitizen":"Senior Citizen Rate"

}, inplace=True)

cluster_profile

from sklearn.preprocessing import MinMaxScaler

heatmap_data = cluster_profile.copy()

scaler = MinMaxScaler()

heatmap_scaled = pd.DataFrame(
    scaler.fit_transform(heatmap_data),
    columns=heatmap_data.columns,
    index=heatmap_data.index
)

plt.figure(figsize=(10,6))

sns.heatmap(
    heatmap_scaled,
    annot=cluster_profile,      # Show original values
    fmt=".2f",
    cmap="YlGnBu"
)

plt.title("Normalized Customer Segment Characteristics")

plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="Customer_Segment",
    y="tenure"
)

plt.title("Tenure by Customer Segment")
plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="Customer_Segment",
    y="MonthlyCharges"
)

plt.title("Monthly Charges by Customer Segment")
plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="Customer_Segment",
    y="TotalCharges"
)

plt.title("Total Charges by Customer Segment")
plt.show()

from sklearn.decomposition import PCA

pca = PCA(n_components=2, random_state=42)

X_pca = pca.fit_transform(X_scaled)

plot_df = pd.DataFrame({

    "PC1": X_pca[:,0],
    "PC2": X_pca[:,1],
    "Segment": df["Customer_Segment"]

})

plt.figure(figsize=(8,6))

sns.scatterplot(

    data=plot_df,
    x="PC1",
    y="PC2",
    hue="Segment",
    palette="tab10",
    alpha=0.7

)

plt.title("Customer Segments (PCA Projection)")
plt.show()

from sklearn.preprocessing import MinMaxScaler
import numpy as np

radar_data = cluster_profile.copy()

scaler = MinMaxScaler()

scaled = scaler.fit_transform(radar_data)

radar_scaled = pd.DataFrame(
    scaled,
    columns=radar_data.columns,
    index=radar_data.index
)

labels = radar_scaled.columns.tolist()

angles = np.linspace(
    0,
    2*np.pi,
    len(labels),
    endpoint=False
)

angles = np.concatenate([angles,[angles[0]]])

fig = plt.figure(figsize=(8,8))
ax = plt.subplot(111, polar=True)

for idx in radar_scaled.index:

    values = radar_scaled.loc[idx].tolist()
    values += values[:1]

    ax.plot(
        angles,
        values,
        linewidth=2,
        label=f"Cluster {idx}"
    )

    ax.fill(
        angles,
        values,
        alpha=0.1
    )

ax.set_xticks(angles[:-1])
ax.set_xticklabels(labels)

plt.legend(loc="upper right")

plt.title("Normalized Customer Segment Profiles")

plt.show()

segment_names = {

    0: "Established Premium",
    1: "Loyal Premium",
    2: "High-Risk New",
    3: "Budget Customers"

}

df["Segment_Name"] = df["Customer_Segment"].map(segment_names)

# ==========================================================
# INSTALL ECONML
# ==========================================================

!pip -q install econml dowhy

# ==========================================================
# IMPORTS
# ==========================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from dowhy import CausalModel

# ==========================================================
# PREPARE DATA
# ==========================================================

econ_df = df.copy()

encode_cols = [

    "gender",
    "Partner",
    "Dependents",
    "PhoneService",
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaperlessBilling",
    "PaymentMethod"

]

for col in encode_cols:
    econ_df[col] = LabelEncoder().fit_transform(econ_df[col])